jwt:
  config:
    key: tmatems
    ttl: 7200000
server:
  port: 8090
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tmatems?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
#配置mybatisplus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: uuid
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值（默认 0）
    banner: true
# 解决中文乱码的问题
  spring:
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
        uri-encoding: UTF-8
